import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { mdToPdf } from 'md-to-pdf';
import logger from '../utils/logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Generate a PDF report from research findings.
 *
 * @param {object} research — structured research data from the Research Agent
 * @param {object} clientData — parsed Tally form data
 * @returns {Buffer} PDF buffer
 */
export async function generateReport(research, clientData) {
  logger.info({ clientName: clientData.businessName }, 'Report Generator → building markdown');

  const markdown = buildReportMarkdown(research, clientData);

  const pdf = await mdToPdf(
    { content: markdown },
    {
      pdf_options: {
        format: 'A4',
        margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
        printBackground: true,
      },
      css: `
        body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; line-height: 1.6; }
        h1 { color: #7c3aed; border-bottom: 3px solid #7c3aed; padding-bottom: 8px; }
        h2 { color: #2563eb; margin-top: 30px; }
        h3 { color: #059669; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; }
        th { background: #f3f4f6; font-weight: 600; }
        blockquote { border-left: 4px solid #7c3aed; padding-left: 16px; color: #4b5563; }
        code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
        .strengths { color: #059669; } .weaknesses { color: #dc2626; }
        .opportunities { color: #2563eb; } .threats { color: #d97706; }
      `,
    },
  );

  logger.info({ clientName: clientData.businessName, pdfSize: pdf.content.length }, 'Report Generator → PDF created');
  return pdf.content; // Buffer
}

/**
 * Build the markdown content for the report.
 */
function buildReportMarkdown(research, client) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `# Strategic Research Report: ${client.businessName}

**Prepared by:** Ascend AI Marketing
**Date:** ${now}
**Client Contact:** ${client.contactName} (${client.contactEmail})

---

## Executive Summary

${research.executiveSummary || 'A comprehensive analysis of the client's market position, competitive landscape, and strategic opportunities for their new website.'}

---

## 1. Client Overview

| Detail | Information |
|--------|-------------|
| **Business Name** | ${client.businessName} |
| **Location** | ${client.location || 'N/A'} |
| **Service Areas** | ${client.serviceAreas || 'N/A'} |
| **Years in Business** | ${client.yearsInBusiness || 'N/A'} |
| **Website Goal** | ${client.websiteGoal || 'N/A'} |
| **Current Website** | ${client.hasWebsite ? client.websiteUrl : 'No existing website'} |

**Business Description:** ${client.businessDescription || 'N/A'}

**Competitive Advantage:** ${client.competitiveAdvantage || 'N/A'}

---

## 2. Industry Analysis

${research.industryAnalysis || 'Industry analysis data will be populated by the research agent.'}

---

## 3. Target Audience Analysis

${research.audienceAnalysis || 'Audience analysis data will be populated by the research agent.'}

**Ideal Customer (from client):** ${client.idealCustomer || 'N/A'}

**Problems Solved:** ${client.problemSolved || 'N/A'}

**Customer Hesitations:** ${client.customerHesitations || 'N/A'}

---

## 4. Competitor Analysis

${research.competitorAnalysis || 'Competitor analysis data will be populated by the research agent.'}

---

## 5. Website Audit

${research.websiteAudit || 'No existing website to audit, or audit data pending.'}

---

## 6. SWOT Analysis

### Strengths
${research.swot?.strengths || '- To be determined'}

### Weaknesses
${research.swot?.weaknesses || '- To be determined'}

### Opportunities
${research.swot?.opportunities || '- To be determined'}

### Threats
${research.swot?.threats || '- To be determined'}

---

## 7. Gap Analysis & Recommendations

${research.gapAnalysis || 'Gap analysis and recommendations will be populated by the research agent.'}

---

## 8. Strategic Recommendations for Website

${research.websiteRecommendations || 'Website-specific recommendations will be populated by the research agent.'}

---

*This report was generated by Ascend AI Marketing's autonomous research system. All data was gathered from publicly available sources and the client's onboarding form.*
`;
}

export default { generateReport };
